# Written in 2021 by bysrkh
# Cirebon, Indonesia
# MIT-License

# defines configuration for application

# defines tomcat port
server:
  port: 8888

# defines data source for configuration
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:bysrkh/repository-boot.git
          search-paths:
            - user-boot
#
#logging:
#  level:
#    com.netflix: WARN
#    org.springframework.web: WARN
#    com.thoughtmechanix: DEBUG